apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      enableServiceLinks: false
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: postgres-password
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: rabbitmq-default-pass
            - name: APP_UPLOAD_DIR
              value: "/app/uploads"
            - name: MINIO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: minio-access-key
            - name: MINIO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: minio-secret-key
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: minio-endpoint
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: minio-port
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: minio-bucket
            - name: MINIO_SECURE
              value: "true"
            - name: MINIO_DEFAULT_EXPIRY
              value: "10000"
            - name: MINIO_DEFAULT_REFRESH
              value: "5000"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/uploads
              name: uploads
              subPath: backend
      restartPolicy: Always
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: lidarc-pvc
