name: lidarc

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # für AMQP (Java-Client)
      - "15672:15672" # für Web UI
    environment:
      RABBITMQ_CONFIG_FILE: rabbitmq/rabbit
    volumes:
      - ./rabbitmq/rabbit.conf:/rabbitmq/rabbit.conf:ro #config tells where to fetch definitions from at startup
      - ./rabbitmq/definitions.json:/rabbitmq/definitions.json:ro #schema definitions (exchanges, queues,..)
    networks:
      - ase-network
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000" # API port
      - "9001:9001" # Console port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: aseWS25LiDARC
    volumes:
      - ./data:/data
      #minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - ase-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - ase-network

  minio-mc:
    image: quay.io/minio/mc:latest
    container_name: minio_initializer
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 admin aseWS25LiDARC &&
      /usr/bin/mc mb myminio/basebucket || true
      "
    networks:
      - ase-network
    restart: on-failure

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lidarc_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ase-network

  frontend:
    build:
      context: ./LiDARC-frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"
    networks:
      - ase-network
  backend:
    build:
      context: ./LiDARC-backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      minio-mc:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=postgres
      - RABBITMQ_HOST=rabbitmq
    networks:
      - ase-network
preprocess-worker:
    image: preprocess-lidarc-worker
    build:
      context: ./LiDARC-worker
      dockerfile: Dockerfile-preprocess-worker
    container_name: preprocess-worker
    depends_on:
      minio:
        condition: service_started
        restart: true
      rabbitmq:
        condition: service_started
        restart: true
    networks:
      - ase-network
      
networks:
  ase-network:
    driver: bridge
#possible volume on host
#volumes:
#  minio_data:
#  - ./data:/data
